import "~/styles/globals.css";

import { TRPCReactProvider } from "~/trpc/react";
import { Inter as FontSans } from "next/font/google"
import { cn } from "~/lib/utils";
import Sidenav from "~/components/ui/sidenav";
import { Toaster } from "~/components/ui/sonner"
import UserHeader from "~/components/ui/userAccountHeader";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased",
        fontSans.variable
      )} suppressHydrationWarning={true}>
        <TRPCReactProvider>
          <main className="flex">
            <Sidenav />
            <div className="w-10/12">
              <UserHeader />
              <div className="p-5">
                {children}
              </div>
            </div>
          </main>
          <Toaster />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
